Updated Models and Schemas
OpenLake/Smart-Insti-App pull request #15
Opened 2024-01-31 17:14 UTC by ArinNigam

### **Updated Models**
--------

- Updated models and schemas for backend and frontend
- Changed the models according to the https://docs.google.com/document/d/189hrwe80Gk-FnVDbOJXpI_SU7GgNlPRP/edit as mentioned in this doc.

All the codes works fine as the previous PR.
All the previous screenshots are applicable to this PR as well

Requesting review @henilp105

2024-02-01 10:52 UTC, Aditya062003 requested changes
Add primary_room, credits/length of course , professor_id in courses

2024-02-02 19:23 UTC, ArinNigam commented
@Aditya062003 added changes as suggested by you.
requesting review

2024-02-03 18:28 UTC, ArinNigam commented
I have fixed all the merged conflicts and other errors 
requesting for a quick review/merge on this PR
@henilp105 @Aditya062003

2024-02-04 06:20 UTC, henilp105 approved these changes

2024-02-04 06:21 UTC, merged