user profile with admin screens integration
OpenLake/Smart-Insti-App pull request #17
Opened 2024-01-31 19:25 UTC by SAISURYAtalla

# Pull Request: User Profile Integration and Editable Features

## Description
This pull request enhances the Smart Insti App by introducing a user profile feature and seamlessly integrating it with the existing admin screens. The user profile includes editable fields for personal information and achievements.

## Changes Made
1. **User Profile Screen**: Developed a user profile screen that displays essential information about the user, including name, ID, email, branch, and graduation year.
2. **Editable Fields**: Implemented editable fields for the user's about section, roles, and skills. Achievements can also be added or modified through an editable section.
3. **Integration with Admin Screens**: Integrated the user profile seamlessly with the existing admin screens, creating a cohesive user experience.
4. **Riverpod System Provider**: Utilized the Riverpod state management system to efficiently manage and provide access to user-related data.

## How to Test
1. Launch the Smart Insti App.
2. Navigate to the user profile screen by tapping on the user icon.
3. Explore and edit various sections of the user profile.
4. Navigate between the user profile and admin screens to ensure a smooth transition.

## Additional Information
- **Smart Insti App**: A comprehensive application for efficient management of student and administrative activities in an educational institution.
- **Editable User Profile**: Users can edit their personal information, roles, skills, and achievements for a personalized experience.
- **Riverpod System Provider**: State management is handled through the Riverpod system provider, ensuring a robust and scalable solution.

## Screenshots 
![home](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/c57efe53-0dd4-47fb-8f5d-766b9ae40f51)
![user profile](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/5077ad1a-9497-4feb-9177-37b1b4664b15)
![admin home](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/a709f229-750f-4df7-b310-95bce8e9ed79)

## Checklist
- [ ] All tests passed successfully.
- [ ] Code follows project guidelines and conventions.
- [ ] Documentation is updated to reflect the changes made.
- [ ] Screenshots are attached to showcase the new features.
- [ ] Reviewed and approved by relevant team members.

Requesting review!
@henilp105

2024-02-10 08:24 UTC, henilp105 requested changes
Thanks @SAISURYAtalla, please clean up  the redundant code there is alot of redundant code.

2024-02-10 09:24 UTC, SAISURYAtalla commented on frontend/lib/models/student2.dart
> +class Student {
Sorry for the oversight , it is adjusted in the latest commit .

2024-02-10 09:27 UTC, SAISURYAtalla commented
The changes requested have been made in the latest commit . 

Kindly review @henilp105

2024-02-10 11:37 UTC, henilp105 reviewed
thanks @SAISURYAtalla , Remove redundant code.

2024-02-10 11:37 UTC, henilp105 commented on frontend/lib/constants/dummy_entries.dart
> +// class DummySkills {
Remove redundant code.

2024-02-10 11:37 UTC, henilp105 commented on frontend/lib/routes/routes.dart
> +//       pageBuilder: (context, state) => MaterialPage(child: UserLogin()),
Remove redundant code.

2024-02-10 11:37 UTC, henilp105 commented on frontend/lib/routes/routes.dart
> +// final GoRouter routes = GoRouter(
Remove redundant code.

2024-02-13 12:52 UTC, henilp105 commented
@SAISURYAtalla resolve conflicts.

2024-02-13 12:54 UTC, SAISURYAtalla commented
> @SAISURYAtalla resolve conflicts.

On it .

2024-02-14 10:53 UTC, SAISURYAtalla commented
all conflicts resolved and profile updated along with edit profile and also integrated with auth and remaining PR's

as you can see , the details of the logged in user is only being displayed(which is mine )
![Screenshot 2024-02-14 162203](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/99bcb71c-89be-47c3-8676-8b00c08ddb19)
![Screenshot 2024-02-14 162216](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/4bee647f-9351-4f2c-bd65-0530fc0d40e7)
![Screenshot 2024-02-14 162225](https://github.com/OpenLake/Smart-Insti-App/assets/131685948/10372456-ab05-4bd0-a6ba-2c4951f51e0d)

Requesting re-review @henilp105 @Aditya062003

2024-02-14 15:45 UTC, merged